### ISSUE TITLE
XML file is a link not a file with content 

### ISSUE THREAD

**Issue by tomMisson** [JonathanMSifleet/iTunesXMLReader#1]
You need to upload the file so that we can use its content

**Comment by JonathanMSifleet** [comment]
This is due to symlinking as the iTunes xml file is constantly updated every time a song is listened to. I will fix this tomorrow

**Comment by tomMisson** [comment]
Thanks

**Comment by JonathanMSifleet** [comment]
Should be fixed now. The project may need to be run in eclipse to work properly, can you verify?

**Comment by tomMisson** [comment]
Is fixed and runs properly in eclipse IDE, if there are any further issues, let me know

**Comment by JonathanMSifleet** [comment]
Thank you.
